use_frameworks!

target 'ConsistencyManagerDemo' do
    pod 'ConsistencyManager', :path => '..'
end

target 'ConsistencyManagerDemo-tvOS' do
    pod 'ConsistencyManager', :path => '..'
end

target 'ConsistencyManagerDemoTests' do
    pod 'ConsistencyManager', :path => '..'
end

target 'ConsistencyManagerDemo-tvOSTests' do
    pod 'ConsistencyManager', :path => '..'
end

